site_name: ma
site_dir: dist/site
site_url: https://bzimmer.github.io/ma

repo_url: https://github.com/bzimmer/ma

nav:
    - Home: index.md
    - Commands: commands.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - git-revision-date-localized
  - search
  - tags

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
