# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  CWD:
    sh: git rev-parse --show-toplevel
  APP:
    sh: basename $PWD
  PKG:
    github.com/bzimmer/{{.APP}}
  DIST:
    "{{.CWD}}/dist"
  GO_PACKAGES:
    sh: go list ./...
  COMMIT:
    sh: git rev-parse --short HEAD
  LDFLAGS:
    -ldflags "-X {{.PKG}}.buildCommit={{.COMMIT}} -X {{.PKG}}.buildTime="{{now | date "2006-01-02T15:04:05Z07:00"}}""

tasks:
  default:
    cmds:
      - task: build

  test:
    desc: Run tests
    cmds:
      - mkdir -p {{.DIST}}
      - go test -race -short -count=1 -covermode atomic -coverprofile {{.DIST}}/coverage.txt {{.PKG}}

  test-integration:
    desc: Run integration tests
    deps: [build]
    cmds:
      - mkdir -p {{.DIST}}
      - go test -count=1 -covermode count -coverprofile {{.DIST}}/coverage.txt {{.PKG}}

  cover:
    desc: Visualize test coverage
    deps: [test]
    cmds:
      - go tool cover -html={{.DIST}}/coverage.txt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.DIST}}

  build:
    desc: Build all cmds
    cmds:
      - go build {{.LDFLAGS}} -o {{.DIST}}/{{.APP}} cmd/{{.APP}}/*.go

  install:
    desc: Install {{.APP}}
    cmds:
      - task: build
        vars:
          DIST:
            sh: echo $GOPATH/bin

  lint:
    desc: Runs golint
    cmds:
      - golangci-lint -v run
      - go vet {{catLines .GO_PACKAGES}}

  snapshot:
    desc: Build a snapshot
    cmds:
      - goreleaser release --snapshot --rm-dist
