# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  CWD:
    sh: git rev-parse --show-toplevel
  APP:
    sh: basename $PWD
  PKG:
    github.com/bzimmer/{{.APP}}
  DIST:
    "{{.CWD}}/dist"

tasks:
  default:
    cmds:
      - task: ma

  ma:
    desc: Run the cli
    deps: [build]
    cmds:
      - '{{.DIST}}/ma {{.CLI_ARGS}}'

  test:
    desc: Run tests
    cmds:
      - mkdir -p {{.DIST}}
      - go test -short -count=1 -covermode count -coverprofile {{.DIST}}/coverage.txt ./...

  cover:
    desc: Visualize test coverage
    deps: [test]
    cmds:
      - go tool cover -html={{.DIST}}/coverage.txt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.DIST}}

  build:
    desc: Build all cmds
    cmds:
      - go build -o {{.DIST}}/{{.APP}} cmd/{{.APP}}/*.go

  install:
    desc: Install {{.APP}}
    deps: []
    cmds:
      - task: build
        vars:
          DIST:
            sh: echo $GOPATH/bin
