version: '3'

includes:
  build: ./Taskfile-build.yml

dotenv: [".clean.env"]

tasks:
  default:
    cmds:
      - task -l

  build:
    desc: Build all binaries
    cmds:
      - task: build:build

  test:
    desc: Run all tests
    cmds:
      - task: build:test
